export const products = [
  {
    id: 1,
    name: 'T-Shirt',
    price: 30,
    quantity: 1,
    images: 'tshirt.PNG',
    size: "S",
    season: "Summer",
  },
  {
    id: 2,
    name: 'Pullover',
    price: 60,
    quantity: 1,
    images: 'pullover.PNG',
    size: "XL",
    season: "Winter",
  },
  {
    id: 3,
    name: 'Pants',
    price: 90,
    images: 'pants.PNG',
    size: "L",
    quantity: 1,
    season: "Winter",
  },
  {
    id: 4,
    name: 'Cars Crocs',
    price: 120,
    images: 'shoes.PNG',
    size: "45",
    quantity: 1,
    season: "Summer",
  },
  {
    id: 5,
    name: 'Beanie',
    price: 35,
    images: 'beanie.PNG',
    size: "XL",
    quantity: 1,
    season: "Winter",
  },
  {
    id: 6,
    name: 'North Face Jacke',
    price: 360,
    images: 'jacke.PNG',
    size: "XL",
    quantity: 1,
    season: "Winter",
  },
  {
    id: 6,
    name: 'Jordan 4er',
    price: 800,
    images: 'jordan.PNG',
    size: "XL",
    quantity: 1,
    season: "Winter",
  },
  {
    id: 7,
    name: 'Nike Jogginghose',
    price: 70,
    images: 'jogginghose.PNG',
    size: "XL",
    quantity: 1,
    season: "Summer",
  },
  {
    id: 8,
    name: 'Kurze Hose',
    price: 40,
    images: 'kurzehose.PNG',
    size: "XL",
    quantity: 1,
    season: "Summer",
  },
]

export const productsW = [
  {
    id: 1,
    name: 'Dress',
    price: 450,
    quantity: 1,
    images: 'dress.PNG',
    size: 'S',
  },
  {
    id: 2,
    name: 'Pants',
    price: 120,
    quantity: 1,
    images: 'wpants.PNG',
    size: 'S',
  },
  {
    id: 3,
    name: 'Bag',
    price: 700,
    quantity: 1,
    images: 'prada.PNG',
    size: 'S',
  },
]
